[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run server:prod"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
NIXPACKS_NODE_VERSION = "20"
